#cloud-config
packages: 
  - git
  - unzip
  - python3-pip
  - pipx
  - openjdk-11-jre
write_files:
  - content: | 
      [Unit]
      Description=Runner: run arbitrary commands
      After=default.target
           
      [Service]
      Type=oneshot
      User=root
      Environment="CHERRY_AUTH_TOKEN=${CHERRY_AUTH_TOKEN}"
      Environment="PACKET_AUTH_TOKEN=${PACKET_AUTH_TOKEN}"
      Environment="RUNNER_MACH=${MACHINE}"
      Environment="RUNNER_AUTH=${RUNNER_AUTH}"
      Environment="RUNNER_URL=https://www.itforarchivists.com/siegfried/jobs/bench"
      Environment="PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/go/bin:/root/droid:/root/.local/bin"
      Environment="HOME=/root"
      ExecStart=/root/go/bin/runner
      ExecStart=/root/go/bin/provisioner -delete -host=${HOST}
           
      [Install]
      WantedBy=default.target
    owner: root:root
    permissions: '0644'
    path: /etc/systemd/system/runner.service
  - content: | 
      [bb]
      type = b2
      account = ${BB_ACCOUNT}
      key = ${BB_KEY}
      endpoint = 
    owner: root:root
    permissions: '0644'
    path: /root/.config/rclone/rclone.conf
runcmd:
  - "mkdir -p /root/go/src"
  - "export GOPATH=/root/go"
  - "export HOME=/root"
  - "curl https://rclone.org/install.sh | /bin/bash -s"
  - "rclone config file"
  - "snap install go --classic"
  - "go install github.com/richardlehane/runner/cmd/runner@latest"
  - "go install github.com/richardlehane/provisioner@latest"
  - "cd /root/go/src"
  - "git clone https://github.com/richardlehane/siegfried.git"
  - "cd siegfried"
  - "go install github.com/richardlehane/siegfried/cmd/sf"
  - "go install github.com/richardlehane/siegfried/cmd/roy"
  - "mkdir /root/siegfried"
  - "cp -R cmd/roy/data/. /root/siegfried"
  - "pipx install opf-fido"
  - "pipx ensure path"
  - "mkdir /tmp/droid"
  - "mkdir /root/droid"
  - "wget -P /tmp/droid https://github.com/digital-preservation/droid/releases/download/droid-6.7.0/droid-binary-6.7.0-bin.zip"
  - "unzip /tmp/droid/droid-binary-6.7.0-bin.zip -d /root/droid"
  - "mv /root/droid/droid.sh /root/droid/droid"
  - "chmod +x /root/droid/droid"
  - "chmod +x /root/droid/droid-ui-6.7.0.jar"
  - "chmod +x /root/droid/droid-command-line-6.7.0.jar"
  - "/root/droid/droid -d"
  - [ systemctl, daemon-reload ]
  - [ systemctl, enable, runner.service ]
  - [ systemctl, start, --no-block, runner.service ]
