name: Test
on:
  push:
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: List brew installs
        run: brew list
      - name: Check the siegfried formula
        run: |
          brew remove go@1.15
          brew install go
      - name: Install siegfried
        run: go install github.com/richardlehane/siegfried/cmd/sf@latest
      - name: Test siegfried
        run: $(go env GOPATH)/bin/sf -version
      
